- name: Datadog events on SQS
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        region: "{{ region }}"
        name: "{{ name }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        delay_seconds: "{{ delay_seconds }}"

  rules:
  
    - name: R1 - Datadog - Toxicstock app request latency detected
      condition: |
        event.body.type == "monitor" and
        event.body.monitor_state == "Alert" and 
        event.body.monitor_name is search("Toxicstack slow response time",ignorecase=true) and 
        event.body.monitor_name is not search("TEST",ignorecase=false)
      action:
        run_job_template:
          name: Apply proxy configuration
          organization: Default
          job_args:
            extra_vars:
              delete: true

    - name: R2 - Datadog - catch TESTing Toxicstock app alerts
      condition: |
        event.body.type == "monitor" and
        event.body.monitor_state == "Warn" and 
        event.body.monitor_name is search("Toxicstack slow response time",ignorecase=true) and 
        event.body.monitor_name is search("TEST",ignorecase=false)
      action:
        run_job_template:
          name: Apply proxy configuration
          organization: Default
          job_args:
            extra_vars:
              delete: false

    - name: R3 - Datadog - Monitor resolved
      condition: |
        event.body.type == "monitor" and
        event.body.monitor_state == "OK"
      action:
        debug:

    - name: R4 - Datadog - catch all other events
      condition: event.meta is defined
      action:
        debug:
