- name: Datadog events on SQS
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        region: "{{ region }}"
        name: "{{ name }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        delay_seconds: "{{ delay_seconds }}"

  rules:
  
    - name: R1 - Datadog - catch app alerts
      condition: event.body.monitor_state == "Alert"
      action:
        debug:

    - name: R2 - Datadog - catch all events
      condition: event.meta is defined
      action:
        debug:
