- name: Golfball events
  hosts: localhost
  sources:
    - kubealex.eda.mqtt:
        host: "{{ host}}"
        port: "{{ port}}"
        topic: "{{ topic }}"

  rules:
    - name: New player starting
      condition: event.command == "new_player"
      action:
        debug:

    - name: Putt made
      condition: event.data == "ST_MAGNET_STOP"
      action:
        run_job_template:
          name: Mastodon post
          organization: Default
          job_args:
            extra_vars:
              mastodon_message: "New putt made in {{ event.stroke }}!"

    - name: Hole in one
      condition: event.data == "ST_MAGNET_STOP" and event.stroke == 1
      action:
        run_job_template:
          name: Mastodon post
          organization: Default
          job_args:
            extra_vars:
              mastodon_message: "Talk about a hole in {{ event.stroke }}!"
