- name: Golfball events
  hosts: localhost
  sources:
    - kubealex.eda.mqtt:
        host: "{{ host}}"
        port: "{{ port}}"
        topic: "{{ topic }}"

  rules:
    - name: New player starting
      condition: event.command == "new_player"
      action:
        debug:

    - name: Putt made
      condition: event.data == "ST_MAGNET_STOP" and event.stroke > 1
      action:
        run_job_template:
          name: Mastodon post
          organization: Default
          job_args:
            extra_vars:
              mastodon_message: "New putt made in {{ event.stroke }} stroke! \n\n Event received at {{ event.meta.received_at }} by #eventdriven #ansible at #rhsummit"

    - name: Hole in one
      condition: event.data == "ST_MAGNET_STOP" and event.stroke == 1
      action:
        run_job_template:
          name: Mastodon post
          organization: Default
          job_args:
            extra_vars:
              mastodon_message: "Talk about a hole in {{ event.stroke }}! \n\n Event received at {{ event.meta.received_at }} by #eventdriven #ansible at #rhsummit \n https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZzZsMW94OWNmcHZoMGc0cGN2bmJucjIxOXZkZ3k2dnFnY2R1ZG52ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/akiHW8qDydkm4/giphy.gif"
