---
- name: Respond to Jira events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: New linux account
      condition: |
        event.payload.fields.customfield_10114.requestType.name == "New Linux Account Request" and 
        event.payload.fields.issuetype.namedValue == "[System] Service request"
      action:
        debug:
