---
- name: Respond to ServiceNow catalog request items
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:

    - name: Enrich new REQ received from Service Catalog
      condition: event.payload.sys_class_name == "sc_request"
      action:
        run_job_template:
          name: "Lookup ServiceNow REQ"
          organization: Default
          post_events: true

    - name: New VM request
      condition: 
        all:
          - events.ritm << event.enriched_event.ritm_details is selectattr('cat_item.display_value', '==', "Provision VM (colin demo)")
          - event.meta is defined
      action:
        debug:
          var: event.enriched_event.ritm_details

    - name: Catch all other events
      condition: true
      action:
        debug:
