- name: SNOW events via webhook
  hosts: localhost
  sources:
    - name: EDA SNOW notification service
      ansible.eda.webhook:
        port: 5001
        host: 0.0.0.0
      filters:
        - cloin.eda.poster:
            webhook_url: 
            
  rules:
    - name: R1 - New POST with content
      condition: |
        event.content.key == "value"
      action:
        debug:

    - name: R2 - Catch high priority incidents
      condition: |
        event.payload.sys_class_name == "incident" and 
        event.payload.impact < 3
      action:
        debug:
