---
- name: Respond to ServiceNow catalog request items
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:

    - name: Enrich new REQ received from Service Catalog
      condition: event.payload.sys_class_name == "sc_request"
      action:
        run_job_template:
          name: "Lookup ServiceNow REQ"
          organization: Default
          post_events: true

    - name: New VM request
      condition:
        all:
          - event.enriched_event.ritm_details is search("Provision VM (colin demo)", ignorecase=true)
          - events.ritm << fact.enriched_event.ritm_details is selectattr('cat_item.display_value', 'contains', "Provision VM (colin demo)")
      action:
        debug:
          var: event.ritm

    - name: Catch all other events
      condition: true
      action:
        debug:
